// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjkarlxalsxghkcmxqvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqa2FybHhhbHN4Z2hrY214cXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjQyMjUsImV4cCI6MjA3MjE0MDIyNX0.l6UTmySYUnyxpvUgCAMLrkVc1Cy4D8DNEEuNItFUwPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});